using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BulkyMerge.SourceGenerators;

[Generator]
public sealed class BulkyMergeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "BulkyMerge.BulkyMergeMappableAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(types, static (spc, symbols) =>
        {
            if (symbols.IsDefaultOrEmpty)
                return;

            foreach (var symbol in symbols.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                spc.AddSource(
                    $"{symbol.Name}BulkMetadata.g.cs",
                    SourceText.From(BulkyMergeGenerator.BuildMetadata(symbol), Encoding.UTF8));
            }
        });
    }

    private static string BuildMetadata(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();

        var tableAttr = type.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "TableAttribute");
        var tableName = tableAttr?.ConstructorArguments.FirstOrDefault().Value as string ?? type.Name;
        var schema = tableAttr?.NamedArguments.FirstOrDefault(n => n.Key == "Schema").Value.Value as string;

        var properties = type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public
                        && p.GetMethod is not null
                        && !HasAttribute(p, "IgnoreAttribute")
                        && !HasAttribute(p, "NotMappedAttribute"))
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using BulkyMerge.Metadata;");
        if (ns is not null)
            sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"partial class {type.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    private sealed class GeneratedBulkMetadata : IBulkMetadata<{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static readonly GeneratedBulkMetadata Instance = new();");
        sb.AppendLine($"        public System.Type EntityType => typeof({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)});");
        sb.AppendLine($"        public string TableName => \"{tableName}\";");
        sb.AppendLine($"        public string? Schema => {(schema is null ? "null" : $"\"{schema}\"")};");
        sb.AppendLine("        public System.Collections.Generic.IReadOnlyList<ColumnDescriptor> Columns { get; } =");
        sb.AppendLine("        [");

        foreach (var prop in properties)
        {
            var column = prop.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name is "ColumnAttribute")
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? prop.Name;
            var isKey = HasAttribute(prop, "KeyAttribute");
            sb.AppendLine(
                $"            new ColumnDescriptor(\"{column}\", \"{prop.Name}\", typeof({prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}), {isKey.ToString().ToLowerInvariant()}, 0),");
        }

        sb.AppendLine("        ];");
        sb.AppendLine("        public System.Collections.Generic.IReadOnlyList<string> KeyColumns { get; } =");
        sb.AppendLine("            Columns.Where(c => c.IsKey).Select(c => c.Name).ToArray();");
        sb.AppendLine();
        sb.AppendLine($"        public object? GetValue({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} entity, int columnIndex)");
        sb.AppendLine("            => columnIndex switch");
        sb.AppendLine("            {");

        for (var i = 0; i < properties.Length; i++)
            sb.AppendLine($"                {i} => entity.{properties[i].Name},");

        sb.AppendLine("                _ => throw new System.ArgumentOutOfRangeException(nameof(columnIndex)),");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine($"        public void SetValue({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} entity, int columnIndex, object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (columnIndex)");
        sb.AppendLine("            {");

        for (var i = 0; i < properties.Length; i++)
        {
            var prop = properties[i];
            sb.AppendLine($"                case {i}:");
            sb.AppendLine($"                    entity.{prop.Name} = ({prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})value!;");
            sb.AppendLine("                    break;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new System.ArgumentOutOfRangeException(nameof(columnIndex));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static IBulkMetadata<" + type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "> BulkMetadata");
        sb.AppendLine("        => GeneratedBulkMetadata.Instance;");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName)
        => symbol.GetAttributes().Any(a => a.AttributeClass?.Name == attributeName);
}
