<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BulkyMerge</RootNamespace>
    <AssemblyName>BulkyMerge.Core</AssemblyName>
    <Description>Core engine for BulkyMerge bulk database operations.</Description>
    <PackageId>BulkyMerge.Core</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BulkyMerge.Abstractions\BulkyMerge.Abstractions.csproj" />
  </ItemGroup>
</Project>
